package fix

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/stribog-cloud/kubevigil/internal/checker"
)

// ResourceID uniquely identifies a Kubernetes resource for patch grouping.
type ResourceID struct {
	Kind      string
	Name      string
	Namespace string
}

// GenerateKustomizeOverlay creates a Kustomize overlay directory with strategic
// merge patches for all applied fixes in the plan. The overlay includes a
// kustomization.yaml and one patch file per resource.
func GenerateKustomizeOverlay(plan *Plan, outputDir string) error {
	// Collect only applied results.
	var applied []Result
	for i := range plan.Summary.Results {
		if plan.Summary.Results[i].Applied {
			applied = append(applied, plan.Summary.Results[i])
		}
	}

	if len(applied) == 0 {
		slog.Info("no applied fixes, skipping Kustomize overlay generation")
		return nil
	}

	// Group results by ResourceID.
	groups := make(map[ResourceID][]PlannedFix)
	for i := range applied {
		result := &applied[i]
		id := ResourceID{
			Kind:      result.Kind,
			Name:      result.Resource,
			Namespace: result.Namespace,
		}

		// Look up the matching PlannedFix from the plan's Files.
		pf := findPlannedFix(plan, result)
		if pf != nil {
			groups[id] = append(groups[id], *pf)
		}
	}

	if len(groups) == 0 {
		return nil
	}

	// Create output directory.
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	// Warn if kustomization.yaml already exists.
	kustPath := filepath.Join(outputDir, "kustomization.yaml")
	if _, err := os.Stat(kustPath); err == nil {
		slog.Warn("kustomization.yaml already exists, will be overwritten", "path", kustPath)
	}

	// Determine the risk level from the applied fixes for the comment.
	riskLevel := highestRiskLevel(applied)

	// Generate patch files.
	var patchFiles []string
	for id, fixes := range groups {
		patchContent, err := buildPatch(id, fixes)
		if err != nil {
			slog.Warn("error building patch", "resource", id.Name, "kind", id.Kind, "error", err)
			continue
		}

		filename := resourcePatchFilename(id)
		patchPath := filepath.Join(outputDir, filename)
		if err := os.WriteFile(patchPath, patchContent, 0o644); err != nil { //nolint:gosec // YAML patch file; world-readable is intentional.
			return fmt.Errorf("writing patch file %s: %w", filename, err)
		}
		patchFiles = append(patchFiles, filename)
	}

	sort.Strings(patchFiles)

	// Generate kustomization.yaml.
	kustContent := buildKustomization(patchFiles, riskLevel)
	if err := os.WriteFile(kustPath, kustContent, 0o644); err != nil { //nolint:gosec // YAML config file; world-readable is intentional.
		return fmt.Errorf("writing kustomization.yaml: %w", err)
	}

	slog.Info("Kustomize overlay generated",
		"dir", outputDir,
		"patches", len(patchFiles),
	)

	return nil
}

// buildKustomization generates the kustomization.yaml content listing all patch files.
func buildKustomization(patchFiles []string, riskLevel RiskLevel) []byte {
	sorted := make([]string, len(patchFiles))
	copy(sorted, patchFiles)
	sort.Strings(sorted)

	var b strings.Builder
	fmt.Fprintf(&b, "apiVersion: kustomize.config.k8s.io/v1beta1\n")
	fmt.Fprintf(&b, "kind: Kustomization\n")
	fmt.Fprintf(&b, "\n")
	fmt.Fprintf(&b, "# Generated by KubeVigil fix (risk level: %s)\n", riskLevel)
	fmt.Fprintf(&b, "# Apply with: kubectl apply -k <overlay-dir>\n")
	fmt.Fprintf(&b, "\n")
	fmt.Fprintf(&b, "patches:\n")
	for _, f := range sorted {
		fmt.Fprintf(&b, "  - path: %s\n", f)
	}

	return []byte(b.String())
}

// buildPatch generates a strategic merge patch YAML for a single resource
// combining all planned fixes.
func buildPatch(id ResourceID, fixes []PlannedFix) ([]byte, error) {
	apiVersion := defaultAPIVersion(id.Kind)

	// Build the patch document structure.
	patch := map[string]any{
		"apiVersion": apiVersion,
		"kind":       id.Kind,
		"metadata":   buildMetadata(id),
	}

	// Separate container-level fixes from pod-level fixes.
	containerFixes := make(map[string][]PlannedFix) // container name -> fixes
	var podFixes []PlannedFix

	for i := range fixes {
		if fixes[i].Finding.Container != "" && isContainerPath(fixes[i].Strategy.FieldPath) {
			containerFixes[fixes[i].Finding.Container] = append(
				containerFixes[fixes[i].Finding.Container], fixes[i])
		} else {
			podFixes = append(podFixes, fixes[i])
		}
	}

	// Build the spec structure.
	spec := buildPodFixesSpec(podFixes, id.Kind)
	containerList := buildContainerPatches(containerFixes)

	// Merge container list into the correct spec location.
	if len(containerList) > 0 {
		insertContainers(spec, containerList, id.Kind)
	}

	if len(spec) > 0 {
		patch["spec"] = spec
	}

	out, err := yaml.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshaling patch: %w", err)
	}

	return out, nil
}

// resourcePatchFilename generates a sanitized filename for a resource patch.
// Format: <kind>-<namespace>-<name>.yaml (or <kind>-<name>.yaml if no namespace).
func resourcePatchFilename(id ResourceID) string {
	parts := []string{strings.ToLower(id.Kind)}
	if id.Namespace != "" {
		parts = append(parts, sanitizeFilename(id.Namespace))
	}
	parts = append(parts, sanitizeFilename(id.Name))
	return strings.Join(parts, "-") + ".yaml"
}

// sanitizeFilename replaces non-alphanumeric characters (except hyphen) with hyphens.
var nonAlphanumericRe = regexp.MustCompile(`[^a-z0-9-]+`)

func sanitizeFilename(s string) string {
	s = strings.ToLower(s)
	s = nonAlphanumericRe.ReplaceAllString(s, "-")
	s = strings.Trim(s, "-")
	return s
}

// defaultAPIVersion returns a reasonable default apiVersion for a given Kind.
func defaultAPIVersion(kind string) string {
	switch kind {
	case "Deployment", "StatefulSet", "DaemonSet", "ReplicaSet":
		return "apps/v1"
	case "Job", "CronJob":
		return "batch/v1"
	default:
		return "v1"
	}
}

// buildMetadata constructs the metadata map for a patch resource.
func buildMetadata(id ResourceID) map[string]any {
	meta := map[string]any{
		"name": id.Name,
	}
	if id.Namespace != "" {
		meta["namespace"] = id.Namespace
	}
	return meta
}

// isContainerPath returns true if the field path contains a container reference.
func isContainerPath(fieldPath string) bool {
	return strings.Contains(fieldPath, "containers[")
}

// buildPodFixesSpec builds the spec map for pod-level fixes (not container-scoped).
func buildPodFixesSpec(fixes []PlannedFix, kind string) map[string]any {
	spec := make(map[string]any)

	for i := range fixes {
		fix := &fixes[i]
		path := fix.Strategy.FieldPath
		// Strip the "spec." prefix since we're building the spec map.
		path = strings.TrimPrefix(path, "spec.")

		setNestedValue(spec, path, fix.Strategy.DesiredValue)
	}

	// Wrap in template if needed for workload kinds.
	if needsTemplateWrap(kind) && len(spec) > 0 {
		spec = map[string]any{
			"template": map[string]any{
				"spec": spec,
			},
		}
	}

	return spec
}

// buildContainerPatches builds a list of container patch entries
// with the container name as the merge key.
func buildContainerPatches(containerFixes map[string][]PlannedFix) []map[string]any {
	if len(containerFixes) == 0 {
		return nil
	}

	// Sort container names for deterministic output.
	names := make([]string, 0, len(containerFixes))
	for name := range containerFixes {
		names = append(names, name)
	}
	sort.Strings(names)

	var containers []map[string]any
	for _, name := range names {
		fixes := containerFixes[name]
		container := map[string]any{
			"name": name,
		}

		for j := range fixes {
			fix := &fixes[j]
			// Extract the path after "containers[*]." or "containers[N].".
			subPath := extractContainerSubPath(fix.Strategy.FieldPath)
			if subPath == "" {
				continue
			}
			setNestedValue(container, subPath, fix.Strategy.DesiredValue)
		}

		containers = append(containers, container)
	}

	return containers
}

// extractContainerSubPath extracts the path portion after the containers array reference.
// e.g., "spec.containers[*].securityContext.privileged" -> "securityContext.privileged"
func extractContainerSubPath(fieldPath string) string {
	idx := strings.Index(fieldPath, "containers[")
	if idx == -1 {
		return ""
	}
	// Find the closing bracket and skip the dot.
	rest := fieldPath[idx:]
	closeBracket := strings.Index(rest, "]")
	if closeBracket == -1 {
		return ""
	}
	sub := rest[closeBracket+1:]
	return strings.TrimPrefix(sub, ".")
}

// insertContainers places the container list at the correct spec path
// based on the resource kind.
func insertContainers(spec map[string]any, containers []map[string]any, kind string) {
	if needsTemplateWrap(kind) {
		// Navigate or create spec.template.spec.containers.
		tmpl, ok := spec["template"].(map[string]any)
		if !ok {
			tmpl = make(map[string]any)
			spec["template"] = tmpl
		}
		tmplSpec, ok := tmpl["spec"].(map[string]any)
		if !ok {
			tmplSpec = make(map[string]any)
			tmpl["spec"] = tmplSpec
		}
		tmplSpec["containers"] = containers
	} else {
		spec["containers"] = containers
	}
}

// needsTemplateWrap returns true if the kind requires spec.template.spec wrapping.
func needsTemplateWrap(kind string) bool {
	switch kind {
	case "Deployment", "StatefulSet", "DaemonSet", "ReplicaSet", "Job":
		return true
	default:
		return false
	}
}

// setNestedValue sets a value at a dot-separated path within a nested map structure.
// Intermediate maps are created as needed.
func setNestedValue(m map[string]any, path string, value any) {
	parts := strings.Split(path, ".")
	current := m

	for i, part := range parts {
		if i == len(parts)-1 {
			// Last part: set the value.
			current[part] = value
			return
		}

		// Navigate or create intermediate map.
		next, ok := current[part].(map[string]any)
		if !ok {
			next = make(map[string]any)
			current[part] = next
		}
		current = next
	}
}

// findPlannedFix locates the matching PlannedFix in the plan for a given result.
func findPlannedFix(plan *Plan, result *Result) *PlannedFix {
	fp, ok := plan.Files[result.FilePath]
	if !ok {
		return nil
	}

	for i := range fp.Fixes {
		pf := &fp.Fixes[i]
		if pf.Applied &&
			pf.Finding.Checker == result.CheckID &&
			pf.Finding.Resource == result.Resource {
			return pf
		}
	}

	return nil
}

// highestRiskLevel determines the highest risk level among applied results.
func highestRiskLevel(results []Result) RiskLevel {
	hasPotentiallyBreaking := false
	hasLikelySafe := false

	for i := range results {
		switch results[i].Safety {
		case checker.FixPotentiallyBreaking:
			hasPotentiallyBreaking = true
		case checker.FixLikelySafe:
			hasLikelySafe = true
		}
	}

	if hasPotentiallyBreaking {
		return RiskLevelAggressive
	}
	if hasLikelySafe {
		return RiskLevelModerate
	}
	return RiskLevelSafe
}
