apiVersion: v1
kind: Namespace
metadata:
  name: kubevigil-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevigil-webhook
  namespace: kubevigil-system
  labels:
    app.kubernetes.io/name: kubevigil-webhook
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: kubevigil-webhook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubevigil-webhook
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: webhook
          # Pin to a released tag in production, e.g. ghcr.io/stribog-cloud/kubevigil:1.2.0
          image: ghcr.io/stribog-cloud/kubevigil:latest
          args:
            - webhook
            - --addr=:8443
            - --tls-cert=/tls/tls.crt
            - --tls-key=/tls/tls.key
            - --fail-on=high
          ports:
            - name: https
              containerPort: 8443
          livenessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tls
              mountPath: /tls
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: kubevigil-webhook-tls
---
apiVersion: v1
kind: Service
metadata:
  name: kubevigil-webhook
  namespace: kubevigil-system
spec:
  selector:
    app.kubernetes.io/name: kubevigil-webhook
  ports:
    - name: https
      port: 443
      targetPort: https
